name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      #  Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      #  Install dependencies
      - name: Install dependencies
        run: npm ci

      #  Build the project
      - name: Build
        run: npm run build

      #  Run tests
      - name: Run Jest tests
        run: npm test -- --watchAll=false

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      #  Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      #  Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel

      #  Pull Vercel project settings (requires token and project ID)
      - name: Pull Vercel environment info
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      #  Build the project for Vercel
      - name: Build project
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      #  Deploy to Vercel
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
